[package]
name = "edlib-rs"
version = "0.1.0"
authors = ["jeanpierre.both@gmail.com"]
edition = "2018"
build = "build.rs"
license = "MIT/Apache-2.0"


[lib]
lib = "edlib_rs"
path = "src/lib.rs"

[build-dependencies]

bindgen = "0.55.1"
